# Generated by Django 2.1.1 on 2019-02-10 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongID', models.IntegerField()),
                ('SongName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('AddDate', models.DateField()),
            ],
            options={
                'ordering': ('SongID',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.IntegerField()),
                ('TypeName', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'ordering': ('TypeID',),
            },
        ),
        migrations.AddField(
            model_name='song',
            name='TypeName',
            field=models.ForeignKey(db_column='TypeName', on_delete=django.db.models.deletion.CASCADE, to='ML.Type'),
        ),
    ]
